// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231007182935_init1")]
    partial class init1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication1.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Login")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nom")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Prenom")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Role")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Situation")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.ToTable("users");
                });

            modelBuilder.Entity("WebApplication1.Models.PatientAyantDroit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CodeCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CodeSCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<string>("PatientsIpp")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PatientsIpp");

                    b.ToTable("patientsAyantDroits");
                });

            modelBuilder.Entity("WebApplication1.Models.PatientBebe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CodeCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CodeSCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<string>("NumAdmissionMere")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PatientsIpp")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PatientsIpp");

                    b.ToTable("patientsBebe");
                });

            modelBuilder.Entity("WebApplication1.Models.PatientCnam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CodeCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CodeSCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<int>("IndexAssure")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Lien_Parente")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Matricule_Assure")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("PatientsIpp")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PatientsIpp");

                    b.ToTable("patientsCnam");
                });

            modelBuilder.Entity("WebApplication1.Models.PatientCp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CodeCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CodeSCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<string>("PatientsIpp")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PatientsIpp");

                    b.ToTable("patientsCp");
                });

            modelBuilder.Entity("WebApplication1.Models.patientMiltaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AnneeRec")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("NVARCHAR2(4)");

                    b.Property<string>("Armee")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<int>("CodeCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CodeCorps")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CodeGrade")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CodeSCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<string>("MatriculeRec")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("PatientsIpp")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PatientsIpp");

                    b.ToTable("patientMiltaires");
                });

            modelBuilder.Entity("WebApplication1.Models.Patients", b =>
                {
                    b.Property<string>("Ipp")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Adresse_Ar")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Adresse_Fr")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Carte_Identite")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Code_Postal")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Date_Cin")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Date_Naissance")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Lieu_Naissance")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Nom_Patient_Ar")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nom_Patient_Fr")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Passeport")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Prenom_Patient_Ar")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Prenom_Patient_Fr")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Prenom_Pere_Ar")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Prenom_Pere_Fr")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Sexe")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telephone1")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telephone2")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Ville")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Ipp");

                    b.ToTable("patients");
                });

            modelBuilder.Entity("WebApplication1.Models.porteurCarteSoins", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CodeCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int>("CodeSCategorie")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("CreatedAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("DateValidite")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Identifiant")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("NVARCHAR2(16)");

                    b.Property<string>("NumCarteSoin")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)");

                    b.Property<string>("PatientsIpp")
                        .HasColumnType("NVARCHAR2(450)");

                    b.Property<string>("Situation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)");

                    b.Property<string>("UpdateAt")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("UpdateBy")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("Id");

                    b.HasIndex("PatientsIpp");

                    b.ToTable("porteurCarteSoins");
                });

            modelBuilder.Entity("WebApplication1.Models.PatientAyantDroit", b =>
                {
                    b.HasOne("WebApplication1.Models.Patients", null)
                        .WithMany("patientsAyantDroits")
                        .HasForeignKey("PatientsIpp");
                });

            modelBuilder.Entity("WebApplication1.Models.PatientBebe", b =>
                {
                    b.HasOne("WebApplication1.Models.Patients", null)
                        .WithMany("patientsBebe")
                        .HasForeignKey("PatientsIpp");
                });

            modelBuilder.Entity("WebApplication1.Models.PatientCnam", b =>
                {
                    b.HasOne("WebApplication1.Models.Patients", null)
                        .WithMany("patientsCnam")
                        .HasForeignKey("PatientsIpp");
                });

            modelBuilder.Entity("WebApplication1.Models.PatientCp", b =>
                {
                    b.HasOne("WebApplication1.Models.Patients", null)
                        .WithMany("patientsCp")
                        .HasForeignKey("PatientsIpp");
                });

            modelBuilder.Entity("WebApplication1.Models.patientMiltaire", b =>
                {
                    b.HasOne("WebApplication1.Models.Patients", null)
                        .WithMany("patientMiltaires")
                        .HasForeignKey("PatientsIpp");
                });

            modelBuilder.Entity("WebApplication1.Models.porteurCarteSoins", b =>
                {
                    b.HasOne("WebApplication1.Models.Patients", null)
                        .WithMany("porteurCarteSoins")
                        .HasForeignKey("PatientsIpp");
                });

            modelBuilder.Entity("WebApplication1.Models.Patients", b =>
                {
                    b.Navigation("patientMiltaires");

                    b.Navigation("patientsAyantDroits");

                    b.Navigation("patientsBebe");

                    b.Navigation("patientsCnam");

                    b.Navigation("patientsCp");

                    b.Navigation("porteurCarteSoins");
                });
#pragma warning restore 612, 618
        }
    }
}
